version: '1'
services:
  - type: web
    name: music-library-api
    runtime: node
    plan: free 
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run migrate && npm start
