version: '1'
services:
  - type: web
    name: music-library-api
    runtime: node
    plan: free # or your chosen plan
    buildCommand: npm install && npm run build # Adjust if you have a build step
    startCommand: npm start
